version: '3.8'

services:
  sapere-front:
    image: vallelabs/sapere-frontend:0.10.2rc1
    container_name: sapere-front
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "tumlab.local:192.168.4.1"
    environment:
      NEXT_PUBLIC_API_URL : http://tumlab.local:4010
      NEXT_PUBLIC_TEMPLATE_CREATE : http://tumlab.local:4010/templates/create-users
    ports:
      - "3003:3000"
    networks:
      - valle-sapere-net
  storage_sapere:
    image: minio/minio:latest
    container_name: storage_sapere
    restart: unless-stopped
    environment:
      MINIO_BUCKET: "${STORAGE_BUCKET_NAME:-sapere-bucket}"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - 'minio_data:/data'
  sapere-back:
    image: vallelabs/sapere-backend:0.6.4-tumlab
    container_name: sapere-back
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "tumlab.local:192.168.4.1"
    environment:
      BACKEND_URL : http://tumlab.local:4010
      DB_DATABASE : sapere
      DB_HOST : host.docker.internal
      DB_PASSWORD : Tumlab2022*
      DB_PORT : 3306
      DB_USER : root
      EMAIL_FROM : test@localhost.local
      EMAIL_HOST : test.localhost.local
      EMAIL_PASSWORD : test
      EMAIL_PORT : 587
      EMAIL_SECURE : false
      EMAIL_USER : test@localhost.local
      KEYCLOAK_AUTH_SERVER_URL : http://tumlab.local:8079/auth
      KEYCLOAK_CLIENT_ID : sapere-client
      KEYCLOAK_DB_ADDR : host.docker.internal
      KEYCLOAK_DB_DATABASE : keycloaksapere
      KEYCLOAK_DB_PASSWORD : Tumlab2022*
      KEYCLOAK_DB_PORT : 5432
      KEYCLOAK_DB_USER : postgres
      KEYCLOAK_ID : 3996c808-3e61-4f03-bdbe-98a8ebc16f7d
      KEYCLOAK_PASSWORD : password
      KEYCLOAK_REALM : ecosistema-auth
      KEYCLOAK_SECRET : 83c720e5-b14d-4322-b4a1-61043d7d6cca
      KEYCLOAK_USER : admin
      NODE_ENV : prod
      PORT : 3000
      STORAGE_API_ENDPOINT : host.docker.internal
      STORAGE_BUCKET_NAME : sapere-bucket
      STORAGE_IS_ENABLED : true
      STORAGE_PORT : 9000
      STORAGE_ACCESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_USE_SSL: false
      SUPPORT_EMAIL : soporte.gestionpedagogica@avefenix.edu.co
      WEB_LOGIN : http://tumlab.local:3003/login
      WEB_SUPPORT : https://soporte.gestionpedagogica.avefenix.edu.co
      CORS_WHITELIST : http://tumlab.local:3003,http://tumlab.local:8079,http://tumlab.local:4010,http://tumlab.local:2999
      IS_TUMLAB : true
    ports:
      - "4010:3000"
    networks:
      - valle-sapere-net
  keycloak:
    image: docker.io/bitnami/keycloak:20
    container_name: sapere_keycloak
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "tumlab.local:192.168.4.1"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: password
      KEYCLOAK_DATABASE_HOST: host.docker.internal
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloaksapere
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: Tumlab2022*
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_BIND_ADDRESS: 0.0.0.0
      KEYCLOAK_ENABLE_STATISTICS: true
      KEYCLOAK_PRODUCTION: false
      KC_HTTP_RELATIVE_PATH: "/auth"
      KEYCLOAK_LOG_LEVEL: INFO
    ports:
      - 8079:8080
    networks:
      - valle-sapere-net

  sapere-game:
    image: vallelabs/sapere-game:2.5.7
    container_name: sapere-game
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "tumlab.local:192.168.4.1"
    ports:
      - "2999:80"
    networks:
      - valle-sapere-net

networks:
  valle-sapere-net:
    driver: bridge
volumes:
  minio_data:
    driver: local
